# This line adds the logo to the browser tab.
# We are now using the full URL to avoid any path issues.
custom_head: '<link rel="icon" type="image/svg+xml" href="https://bg.363689.xyz/icon.svg" />'

# The 'backend' section has been reformatted with correct indentation.
backend:
  name: github
  branch: main # change this to your branch
  repo: xushangjuncn/Astro # 1、change this to your repo
  site_domain: bg.363689.xyz # 2、change this to your domain
  base_url: https://bg.363689.xyz # 3、change this to your prod URL
  auth_endpoint: oauth # the oauth route provided by the integration

# Media files will be stored in this folder in the repository.
media_folder: "public/assets/images"
# The src attribute for uploaded media will begin with this path.
public_folder: "/assets/images"

collections:
  - name: "note"
    label: "笔记"
    folder: "src/content/note"
    create: true
    slug: "{{year}}.{{month}}.{{day}}_{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string", required: true }
      - {
          label: "简介",
          name: "description",
          widget: "string",
          default: "这是一篇有意思的文章",
          required: true,
        }
      - {
          label: "发布日期",
          name: "publishDate",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm",
          required: true,
        }
      - { label: "正文", name: "body", widget: "markdown" }

  - name: "post"
    label: "博文"
    folder: "src/content/post"
    create: true
    slug: "{{year}}.{{month}}.{{day}}_{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string", required: true }
      - {
          label: "简介",
          name: "description",
          widget: "string",
          default: "这是一篇有意思的文章",
          required: true,
        }
      - {
          label: "发布日期",
          name: "publishDate",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm",
          required: true,
        }
      - { label: "标签", name: "tags", widget: "list", required: true }
      - {
          label: "ogImage",
          name: "ogImage",
          widget: "string",
          default: "/social-card.avif",
          required: true,
        }
      - { label: "正文", name: "body", widget: "markdown" }

